####################################### SOURCE SYSTEM ##############################################
# Please fill source details
topology: DR # HA, NONHA, DR
ansible_folder_path: /cm_sap_migration/examples-sap-migration/sc02_standard_hsr_migration_{{ source.sap.sid }}_{{ target.sap.sid }}/ansible
hdbuserstore_key_source:
  required: "yes" #yes,no
  key_name: "BACKUP"  # provide hdbuesrstore key name if you have an existing key, else it will get created
hsr_source:
  mode: "hdbuserstorekey" #user,hdbuserstorekey (provide with which method log mode,hana parameter has to be set)

###################################### TARGET SYSTEM ###############################################    
hdbuserstore_key_target:
  required: "yes" #yes,no
  key_name: "BACKUP"  # provide hdbuesrstore key name if you have an existing key, else it will get created
DR: # replication between source primary to target 
  mode: "hdbuserstorekey" #user,hdbuserstorekey (provide with which method log mode,hana parameter has to be set)
  folders:
    - path: /hana/backup/data
    - path: /hana/backup/data/SYSTEMDB_EMD
    - path: /hana/backup/data/DB_EMD
  backup_type: backup # backup,on_demand_backup(backup with azure recovery vault),aws,veritas,sep,veeam,dell_emc_networker,commvault,arcserve,bacula
  backup_prifix: COMPLETE_DATA_BACKUP
  hana_backup_path: /hana/backup/data/SYSTEMDB_EMD
  hana_tenant_backup_path: /hana/backup/data/SYSTEMDB_EMD
  tenant: 
    - EMD
  on_demand_backup: # on_demand_backup(backup with azure recovery vault)
    resource_group: example-rg-source-app
    vault_name: cloudcoergeastus
    retain_backup_untill: 01-01-2040 # Retention must be between 45 days to 99 years
    backup_start_date: 11-01-2023

copy_files: # copy .dat and .key file from source primary to target
  authentication_type: with_password # with_password, passwordless, ppk_with_passphrase, ppk, pem
  source_root_password: "{{ hsr_passwords.root_source }}" # Please provide password if auth_type is with_password
  host_ip: "{{ hostvars[groups['source_db'][0]].ansible_host }}"
  user: emdadm # root, hdbadm Please provide password if auth_type is with_password  
  ppk_or_pem: # provide ppk and pem path and file name
    ppk_pem_source_path: /cm_sap_migration/examples-sap-migration/sc02_abap_migration_Standard_HSR_sourcesid_targetsid/ansible/   # path of ppk file
    ppk_pem_file_name: fio1.ppk  # fio1.ppk
    ppk_passphrase: "{{ hsr_passwords.ppk_passphrase }}"

replication_dr:  
  #enable_site_hostname: abc #provide the hostname which has to be enabled if it is other than default i.e source hostanme 
  source_db: "{{ source.sap.logical_hosts.db.hostname }}" # {{ source.sap.logical_hosts.db.hostname }} source db name to register( physical or virtual hostname)
  target_db:  "{{ groups['target_db'][0] }}" # target db name to register( physical or virtual hostname)
  replication_mode: async # sync, syncmem, async 
  operation_mode: logreplay #logreplay,logreplay_readaccess, delta_datashipping 
  register_mode: "register" # register, register_online
  full_sync: "no" # only when replication_mode is sync
  time_travel_params:  
    required: "no" 
    value: # timetravel_max_retention_time, timetravel_snapshot_creation_interval (when hana is 2sp5+ )

hana_parameters:
  hana_params_change_target:
    required: "yes" 
    params:
      - service_ini: global.ini # global.ini, indexserver.ini
        set_mode: system_replication # system_replication,inifile_checker
        parameter: enable_lop_retent
        value: "on" # true, false 

host_resolution: # host name resolution for system replication
  source_host: # replication between source and target
    required: "yes" # yes,no
    value: .global #.internal or .global
    entries:
      - hostname: "{{ groups['source_db'][0] }}"
        ip: "{{ hostvars[groups['source_db'][0]].ansible_host }}"
  target_host:
    required: "yes"
    value: .global #.internal or .global
    entries:
      - hostname: "{{ groups['target_db'][0] }}"
        ip: "{{ hostvars[groups['target_db'][0]].ansible_host }}"

source_network_params: 
  required: "yes" #yes, no
  ipv4_values: # Comment filename and value if not required 
    - file_name: tcp_tw_reuse
      value: "2"
    - file_name: tcp_wmem 
      value: "65536 16777216 16777216"
    - file_name: tcp_wmem 
      value: "65536 16777216 16777216"
    - file_name: tcp_max_syn_backlog
      value: "8192"
    - file_name: tcp_slow_start_after_idle
      value: "0"
    - file_name: tcp_timestamps
      value: "1"
    - file_name: tcp_syn_retries
      value: "8"
    - file_name: tcp_window_scaling
      value: "1"
    - file_name: ip_local_port_range
      value: ""
  core_values:
    - file_name: somaxconn_abc
      value: "40968"
    - file_name: wmem_max
      value: "20971520"
    - file_name: rmem_max
      value: "20971520"
  ipv6_values:
    - file_name: 
      value: 
    - file_name: 
      value: 
