---
- name: main | create folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ exp_imp_prechecks.prechecks_output_path }}"
    - "{{ exp_imp_prechecks.source_file_path }}"
    - "{{ exp_imp_prechecks.target_file_path }}"

- name:  main | check 
  include_tasks: "{{ mode }}.yml"