select TOP 1 ENTRY_TYPE_NAME,SYS_START_TIME,SYS_END_TIME,
	SECONDS_BETWEEN(SYS_START_TIME,SYS_END_TIME) as BACKUP_DURATION_IN_SEC,
	SECONDS_BETWEEN(SYS_START_TIME,SYS_END_TIME)/60 as BACKUP_DURATION_IN_MIN,
	'success' as STATUS
	FROM M_BACKUP_catalog where ENTRY_TYPE_NAME in('complete data backup')  
	ORDER BY  sys_start_time desc;
