SELECT TOP 1 FREQUENCY_OF_BACKUP_IN_MIN,COUNT(FREQUENCY_OF_BACKUP_IN_MIN) AS OCCURENCES,'success' AS STATUS FROM
	(SELECT ENTRY_TYPE_NAME,SYS_START_TIME,SYS_END_TIME,
	SECONDS_BETWEEN(SYS_START_TIME,SYS_END_TIME) as FREQUENCY_OF_BACKUP_IN_SEC,
	SECONDS_BETWEEN(SYS_START_TIME,SYS_END_TIME)/60 AS FREQUENCY_OF_BACKUP_IN_MIN
	FROM M_BACKUP_CATALOG  where ENTRY_TYPE_NAME in('incremental data backup') 
	ORDER BY SYS_START_TIME DESC)GROUP BY FREQUENCY_OF_BACKUP_IN_MIN ORDER BY OCCURENCES DESC ;
