####################################### SOURCE SYSTEM ##############################################
# Please fill source details
topology: NONHA # HA, NONHA
ansible_folder_path: /cm_sap_migration/examples-sap-migration/sc02_standard_hsr_migration_{{ source.sap.sid }}_{{ target.sap.sid }}/ansible
hdbuserstore_key_source:
  required: "yes" #yes,no
  key_name: "BACKUP"  # provide hdbuesrstore key name if you have an existing key, else it will get created
hsr_source:
  mode: "hdbuserstorekey" #user,hdbuserstorekey (provide with which method log mode,hana parameter has to be set)
  backup_type: backup # backup,on_demand_backup(backup with azure recovery vault),aws,veritas,sep,veeam,dell_emc_networker,commvault,arcserve,bacula
  # Please fill the details if backup_type is other than on_demand_backup
  backup_prifix: COMPLETE_DATA_BACKUP
  hana_backup_path: /backup/data/SYSTEMDB
  hana_tenant_backup_path: /backup/data/DB_HDB
  tenant: 
    - HDB
  on_demand_backup: # on_demand_backup(backup with azure recovery vault) 
    resource_group: cloudcoe_rg_east_us #example-rg-source-app
    vault_name: cloudcoergeastus
    retain_backup_untill: 01-01-2040 # Retention must be between 45 days to 99 years
    backup_start_date: 11-01-2023

###################################### TARGET SYSTEM ###############################################    

hdbuserstore_key_target:
  required: "yes" #yes,no
  key_name: "BACKUP"  # provide hdbuesrstore key name if you have an existing key, else it will get created
target_primary: # replication between source primary to target 
  mode: "hdbuserstorekey" #user,hdbuserstorekey (provide with which method log mode,hana parameter has to be set)
  folders:
    - path: /hana/backup/data
    - path: /hana/backup/data/SYSTEMDB_EM1
    - path: /hana/backup/data/DB_EM1
  backup_type: backup # backup,on_demand_backup(backup with azure recovery vault),aws,veritas,sep,veeam,dell_emc_networker,commvault,arcserve,bacula
  backup_prifix: COMPLETE_DATA_BACKUP
  hana_backup_path: /backup/data/SYSTEMDB
  hana_tenant_backup_path: /backup/data/DB_HDB
  tenant: 
    - HDB
  on_demand_backup: # on_demand_backup(backup with azure recovery vault)
    resource_group: example-rg-source-app
    vault_name: cloudcoergeastus
    retain_backup_untill: 01-01-2040 # Retention must be between 45 days to 99 years
    backup_start_date: 11-01-2023

copy_files: # copy .dat and .key file from source primary to target
  authentication_type: with_password # with_password, passwordless, ppk_with_passphrase, ppk, pem
  source_root_password: "{{ hsr_passwords.root_source }}" # Please provide password if auth_type is with_password
  host_ip: "{{ hostvars[groups['source_db'][0]].ansible_host }}"
  user: root # root, hdbadm Please provide password if auth_type is with_password  
  ppk_or_pem: # provide ppk and pem path and file name
    ppk_pem_source_path: /cm_sap_migration/examples-sap-migration/sc02_abap_migration_Standard_HSR_sourcesid_targetsid/ansible/   # path of ppk file
    ppk_pem_file_name: fio1.ppk  # fio1.ppk
    ppk_passphrase: "{{ hsr_passwords.ppk_passphrase }}"

replication: 
  #enable_site_hostname: abc #provide the hostname which has to be enabled if it is other than default i.e source hostanme 
  source_db: "{{ groups['source_db'][0] }}" # {{ source.sap.logical_hosts.db.hostname }} source db name to register( physical or virtual hostname)
  target_db:  "{{ groups['target_db'][0] }}" # {{ target.sap.logical_hosts.db.hostname }}target db name to register( physical or virtual hostname)
  replication_mode: async # sync, syncmem, async 
  operation_mode: logreplay #logreplay,logreplay_readaccess, delta_datashipping 
  register_mode: "register" # register, register_online
  full_sync: "no" # only when replication_mode is sync
  time_travel_params:  
    required: "no" 
    value: # timetravel_max_retention_time, timetravel_snapshot_creation_interval (when hana is 2sp5+ )
  take_over_params:
    take_over: "yes"
    suspend_primary: "yes" #yes, no (disables source primary)

cut_over: # provide cut over date and time(server time)
  date: jan 5  # today, tomorrow, jan 10
  time: 1017   # hour and min (10-hr17-min)
#####################################################################################################

hana_parameters:
  hana_params_change_source: # Refer README.MD file
    required: "no"
    params: # Repeat the block for multiple parameters by refering README.md file
      - service_ini: global.ini # global.ini, indexserver.ini
        set_mode: system_replication # system_replication,inifile_checker
        parameter: enable_log_retention
        value: "on" # true, false 
  hana_params_change_target:
    required: "no" 
    params:
      - service_ini: global.ini # global.ini, indexserver.ini
        set_mode: system_replication # system_replication,inifile_checker
        parameter: enable_log_retention
        value: "true" # true, false 

host_resolution: # host name resolution for system replication
  source_host: # replication between source and target
    required: "yes" # yes,no
    value: .global #.internal or .global
    entries:
      - hostname: "{{ groups['source_db'][0] }}"
        ip: "{{ hostvars[groups['source_db'][0]].ansible_host }}"
  target_host:
    required: "yes"
    value: .global #.internal or .global
    entries:
      - hostname: "{{ groups['target_db'][0] }}"
        ip: "{{ hostvars[groups['target_db'][0]].ansible_host }}"

source_network_params: 
  required: "no" #yes, no
  ipv4_values: # Comment filename and value if not required 
    - file_name: tcp_tw_reuse
      value: "2"
    - file_name: tcp_wmem 
      value: "65536 16777216 16777216"
    - file_name: tcp_wmem 
      value: "65536 16777216 16777216"
    - file_name: tcp_max_syn_backlog
      value: "8192"
    - file_name: tcp_slow_start_after_idle
      value: "0"
    - file_name: tcp_timestamps
      value: "1"
    - file_name: tcp_syn_retries
      value: "8"
    - file_name: tcp_window_scaling
      value: "1"
    - file_name: ip_local_port_range
      value: ""
  core_values:
    - file_name: somaxconn
      value: "4096"
    - file_name: wmem_max
      value: "20971520"
    - file_name: rmem_max
      value: "20971520"
  ipv6_values:
    - file_name: 
      value: 
    - file_name: 
      value: 
      