---
abap_pre_migration_list:
  abap:
    - { name: "ZCM_T_CVERS_EXP_SOFTWARE_COMP.txt" }
    - { name: "ZCM_EXP_SYSTEM_STATUS.txt" }
    - { name: "ZCM_SM51_EXP_KERNEL_PATCH.txt" }
    - { name: "ZCM_SM12_EXP_LOCK_ENTRIES.txt" }
    - { name: "ZCM_RZ04_SM63_EXP_OPERAT_MODES.txt" }
    - { name: "ZCM_SMGW_EXP_PRXYINFO.txt" }
    - { name: "ZCM_SMGW_EXP_REGINFO.txt" }
    - { name: "ZCM_SMGW_EXP_SECINFO.txt" }
    - { name: "ZCM_SCC4_EXP_CLIENT_SETTINGS.txt" }
    - { name: "ZCM_ST22_EXP_RUNTIME_ERRORS.txt", input_params: 'EXPORT,{{ ST22_no_of_days }}' }
    - { name: "ZCM_SM51_EXP_INSTANCES.txt" }
    - { name: "ZCM_SM13_EXP_UPDATEREQUEST.txt" }
    - { name: "ZCM_WE02_EXP_FAILED_IDOCS.txt" }
    - { name: "ZCM_WE21_EXP_IDOC_PORTS.txt" }
    - { name: "ZCM_BD54_EXP_LOGICAL_SYSTEMS.txt" }
    - { name: "ZCM_SMICM_EXP_ICM_STATUS.txt" }
    - { name: "ZCM_RZ70_EXP_SLD_REGISTRATION.txt" }
    - { name: "ZCM_RZ70_CHK_SLD_CONNECTION.txt" }
    - { name: "ZCM_SLDAPICUST_EXP_SLDDATA.txt" }
    - { name: "ZCM_STMS_CHK_CONNECTION.txt" }
    - { name: "ZCM_STMS_EXP_IMPORT_QUEUE.txt" }
    # - { name: "ZCM_STMS_EXP_IMPORT_RUNNIG_TRS.txt" }
    - { name: "ZCM_STZAC_EXP_CUSTOM_TIMEZONE.txt" }
    - { name: "ZCM_SFW5_EXP_ACTIVE_BUSINESSFN.txt" }
    - { name: "ZCM_SMQ1_EXP_OUTBOUND_QUEUE.txt" }
    - { name: "ZCM_SMQ2_EXP_INBOUND_QUEUE.txt" }
    - { name: "ZCM_EXP_MISSING_TABLES_INDEX.txt" }
    - { name: "ZCM_T_HTTPURLLOC_EXPORT.txt" }
    - { name: "ZCM_SM61_EXP_SERVER_GROUPS.txt" }
    - { name: "ZCM_SPAD_EXP_PRINTER_LOCKUNLOC.txt" }
    - { name: "ZCM_SP01_EXP_ERRORSTATE_SPOOL.txt" }
    - { name: "ZCM_UNICODE_EXP_STATUS.txt" }
    - { name: "ZCM_SICK_CHK_SAPACCESS.txt" }
    - { name: "ZCM_SM37_EXP_CANCL_SUSPND_REL.txt" }
    - { name: "ZCM_SM35_EXP_BATCH_SESSIONS.txt" }
    - { name: "ZCM_SLDCHECK_CHK_SLDCONNECTION.txt" }
    - { name: "ZCM_SM51_EXP_SNC_STATUS.txt" }
    - { name: "ZCM_SPAD_EXP_OPDEVICE_SERVERS.txt", input_params: "{{ spad_input }}" } 
    - { name: "ZCM_DB13_EXP_DBA_CALENDAR_JOBS.txt" }
    - { name: "ZCM_SE61_EXP_LOGIN_SCREEN_INFO.txt", input_params: 'EXPORT,ZLOGIN_SCREEN_INFO' }
    - { name: "ZCM_SM12_EXP_ENQUEUE_STATISTIC.txt" }      
    - { name: "ZCM_ST03N_EXP_WORKLOAD_HISTORY.txt" }
    - { name: "ZCM_R_FP_TEST_00_CHK_ADS_CONXN.txt", input_params: 'FP_TEST_00,PDF,ADS,D,2,DE,1' }
    - { name: "ZCM_ST02_EXP_BUFFER_PARAMETERS.txt", input_params: LIST }
    - { name: "ZCM_RZ03_EXP_SERVER_STAT_ALRTS.txt" }
    - { name: "ZCM_OSS1_EXP_TECHNICAL_SETTING.txt" }
    - { name: "ZCM_SBGRFCMON_EXP_BGRFCMONITOR.txt" }
    - { name: "ZCM_T_RS_TABLES_EXPORT.txt" }
    - { name: "ZCM_R_RSTPTEST_EXP_TMS_CHECK.txt" }
    - { name: "ZCM_ST06_EXP_SYSTEM_INFO.txt" }
    - { name: "ZCM_SM02_READ_SYSTEM_MESSAGE.txt" }
    - { name: "ZCM_SM69_EXP_OPSYS_COMMANDS.txt" }
    - { name: "ZCM_EXP_SYSTEM_ID.txt" }
    - { name: "ZCM_SIGS_EXP_DETAILS.txt" }
    - { name: "ZCM_SM19_EXP_SEC_AUDIT_PROFILE.txt" }
    - { name: "ZCM_TREXADMIN_EXP_TREXDATA.txt", input_params: 'EXPORT|TREX_NIS' }
    - { name: "ZCM_T_E070L_EXPORT.txt" }
    - { name: "ZCM_T_E070_EXP_REL_OPEN_TR.txt" }
    - { name: "ZCM_SOST_EXP_FAILED_MAILS.txt", input_params: 'EXPORT,{{ SOST_no_of_days }}' }
    - { name: "ZCM_SWU3_EXP_ERROR_NODES.txt" }
    - { name: "ZCM_RZ10_CHECK_PROFILES.txt" }
    - { name: "ZCM_RZ10_EXP_PROFILE_PARAMETER.txt" }
    - { name: "ZCM_SLICENSE_EXP_SETTINGS_LIC.txt" }
    - { name: "ZCM_SMQR_EXP_QUEUE.txt" }
    - { name: "ZCM_SMQS_EXP_DESTINATION.txt" }
    - { name: "ZCM_RZ21_DEL_OLDAPPL_SERV.txt", input_params: "{{ rz21_input }}" } 
    - { name: "ZCM_EXP_RSICFCHK_DETAILS.txt" }
    - { name: "ZCM_SICF_EXP_ACTIVE_SERVICES.txt" }
    - { name: "ZCM_BD64_EXP_DISTRIBUTION_MDL.txt" }
    - { name: "ZCM_SM59_EXP_RFC_DESTINATIONS.txt" }
    - { name: "ZCM_SMLG_EXP_LOGON_GROUPS.txt" }
    - { name: "ZCM_DBCO_EXP_CONNECTION_OVERVW.txt" }
    - { name: "ZCM_DBCO_EXP_CONNECTION_INFO.txt" }
    - { name: "ZCM_STRUSTSSO2_EXP_LOGON_TICKT.txt" }
    - { name: "ZCM_OAM1_EXP_ARCHIVELINK_MONTR.txt" }
    - { name: "ZCM_EXP_SOAMANAGER_WEBSERVICE.txt" }    
    - { name: "ZCM_SE80_EXP_INACTIVE_OBJECTS.txt" }
    - { name: "ZCM_LDAP_EXP_SERVICE_INTERFACE.txt" }
    - { name: "ZCM_SMT1_EXP_TRUSTED_RFC.txt" }
    - { name: "ZCM_SMT2_EXP_TRUSTED_RFC.txt" }
    - { name: "ZCM_SM58_EXPORT_FAILED_TRFC.txt", input_params: 'EXPORT,{{ SM58_no_of_days }}' }
    - { name: "ZCM_DB13_CHK_DB_CONSITENCY.txt" }
    - { name: "ZCM_T_SAPWLSERV_EXPORT.txt" }
    - { name: "ZCM_AL11_EXP_SAP_DIRECTORY.txt" }
    - { name: "ZCM_SP12_EXP_TEMSE_CONSISTENCY.txt" }
    - { name: "ZCM_HDB_DB02_EXP_HOST_SERVICES.txt" } #when: component_version >= "751" and component_version != "752" }

  oracle:
    - { name: "ZCM_ORA_MSS_CHK_DB_ENCRYPTION.txt" }
    - { name: "ZCM_ORACLE_TOP_TABLES_EXP.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_ORACLE_TOP_TABLES_EXP_RCNT.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_ORACLE_TOP_TABLES_EXP_TSIZ.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_T_TAORA_IAORA_CHK_CONSTNCY.txt" }
    - { name: "ZCM_T_TATGPC_TATGPCA_EXPORT.txt" }      
    - { name: "ZCM_ORA_ST04_SYSTEM_PERFORMANC.txt" }
    - { name: "ZCM_ORA_EXPORT_DB_SIZE.txt" }
    - { name: "ZCM_DXB_ST04_EXP_ALERT_MONITOR.txt" }
    - { name: "ZCM_ORA_DB02_CHK_LOGBCKUP_ENBL.txt" }
    - { name: "ZCM_DB13_CHK_DB_STATS.txt" }

  hana:
    - { name: "ZCM_HANA_TOP_TABLES_EXP.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_HANA_TOP_TABLES_EXP_RCNT.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_HANA_TOP_TABLES_EXP_TSIZ.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_HANA_CHK_DB_ENCRYPTION.txt" }
    - { name: "ZCM_DB01_EXP_BLOCKED_TXN_HANA.txt" }
    - { name: "ZCM_HDB_ST04_SYSTEM_PERFORMANC.txt" }
    - { name: "ZCM_HDB_ST04_EXP_ALERT_MONITOR.txt" }
    - { name: "ZCM_HDB_NWBC_CONFIG_OVRVW.txt" }
    - { name: "ZCM_HDB_FIORI_LAUNCH_CHCK.txt" } # component_version == "751" & == "754"
    - { name: "ZCM_HDB_SQL_QUERIES_EXECUTE.txt" }

  sql:
    - { name: "ZCM_ORA_MSS_CHK_DB_ENCRYPTION.txt" }
    - { name: "ZCM_SQLSERVER_TOP_TABLES_EXP.txt" , input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_SQLSERVER_TOP_TABLES_EXP_RCNT.txt" , input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_SQLSERVER_TOP_TABLES_EXP_TSIZ.txt" , input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_DXB_ST04_EXP_ALERT_MONITOR.txt" }   
    - { name: "ZCM_MSS_ST04_SYSTEM_PERFORMANC.txt" }
    - { name: "ZCM_MSSQL_EXP_CURR_FREE_DBSIZE.txt", input_params: FETCH }

  sybase:
    - { name: "ZCM_SYB_CHK_DB_ENCRYPTION.txt" }
    - { name: "ZCM_SYBASE_TOP_TABLES_EXP.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_SYBASE_TOP_TABLES_EXP_RCNT.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_SYBASE_TOP_TABLES_EXP_TSIZ.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_SYB_EXP_LAST_LOG_DB_BACKUP.txt" }
    - { name: "ZCM_SYBASE_EXP_CURR_FREE_DBSIZ.txt" }

  db2:
    - { name: "ZCM_DB2_TOP_TABLES_EXP.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_DB2_TOP_TABLES_EXP_RCNT.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_DB2_TOP_TABLES_EXP_TSIZ.txt", input_params: 'FETCH,100,{{ schema_name }}' }
    - { name: "ZCM_DB2_CHK_DB_ENCRYPTION.txt" }
    - { name: "ZCM_DB2_ST04_SYSTEM_PERFORMANC.txt" }
    - { name: "ZCM_DXB_ST04_EXP_ALERT_MONITOR.txt" }

version_specific_scripts:
  - { name: "ZCM_STRUST_EXP_CERT.txt" }
  - { name: "ZCM_STRUST_EXP_WEBDIS.txt" }
  - { name: "ZCM_EXP_RSPARAM_DETAILS.txt" }
  - { name: "ZCM_EXP_SAP_SYSALIASE.txt" }
  - { name: "ZCM_IWFND_EXP_SERVICE.txt" }
  - { name: "ZCM_OAC0_EXP_CONTENT_REPO.txt" }
  - { name: "ZCM_RSA1_EXP_LOGICAL_STAT.txt" }
  - { name: "ZCM_RSAU_CONFIG_PARAM.txt" } 
  - { name: "ZCM_RZ12_EXP_RFC_GRP.txt" }
  - { name: "ZCM_SCOT_EXP_SMTP_NODES.txt" }
  - { name: "ZCM_SM52_EXP_STATUS.txt" }
  - { name: "ZCM_WE20_EXP_PART_PROFILE.txt" }
  - { name: "ZCM_SE06_EXP_SYS_SETTINGS.txt" }
  - { name: "ZCM_EXP_INSTALL_PROD_VERS.txt" } #supportpackage_version > "0000"
  - { name: "ZCM_SECSTORE_EXP_CONTENTS.txt" }
  - { name: "ZCM_SM13_EXP_ADMIN_DT.txt" }
  - { name: "ZCM_SM21_EXP_SYSTEM_LOGS.txt", input_params: 'EXPORT,{{ SM21_no_of_days }}' }
  - { name: "ZCM_SMICM_CHK_HTTP_SMTP.txt" }
  - { name: "ZCM_CHK_RFC_CONNECTIONS.txt" }

abap_pre_migration_list_clients:
  - { name: "ZCM_SMQ1_EXP_OUTBOUND_QUEUE.txt" }
  - { name: "ZCM_SMQ2_EXP_INBOUND_QUEUE.txt" }
  - { name: "ZCM_SMQR_EXP_QUEUE.txt" }
  - { name: "ZCM_SMQS_EXP_DESTINATION.txt" }
  - { name: "ZCM_WE20_EXP_PART_PROFILE.txt" }
  - { name: "ZCM_WE02_EXP_FAILED_IDOCS.txt" }
  - { name: "ZCM_WE21_EXP_IDOC_PORTS.txt" }        
  - { name: "ZCM_SCOT_EXP_SMTP_NODES.txt" }
  - { name: "ZCM_RSA1_EXP_LOGICAL_SYS_STATS.txt" }
  - { name: "ZCM_BD64_EXP_DISTRIBUTION_MDL.txt" }
  - { name: "ZCM_SOST_EXP_FAILED_MAILS.txt" }
  - { name: "ZCM_SWU3_EXP_ERROR_NODES.txt" }

os_queries_windows:
  - { name: "get_hostname_details", query: "hostname", when: os_type == 'windows' }
  - { name: "get_webdispatcher_details", query: "disp+work", when: os_type == 'windows' }
  - { name: "get_webdispatcher_version_details", query: "sapwebdisp -version", when: os_type == 'windows' }
  - { name: "get_systeminfo", query: "systeminfo", when: os_type == 'windows' }
  - { name: "get_disklayout", query: "wmic logicaldisk get size,freespace,caption", when: os_type == 'windows' } 

os_queries_linux:
  - { name: "get_hostname", query: "hostname", when: os_type == 'linux' }
  - { name: "get_lscpu_details", query: "lscpu", when: os_type == 'linux' }
  - { name: "get_webdispatcher", query: "disp+work", when: os_type == 'linux' }
  - { name: "get_webdispatcher_version", query: "sapwebdisp -version", when: os_type == 'linux' }
  - { name: "get_ulimit", query: "ulimit -a", when: os_type == 'linux' }
  - { name: "get_host_details", query: "cat /etc/hosts", when: os_type == 'linux' }
  - { name: "get_service_files", query: "cat /etc/services", when: os_type == 'linux' }
  - { name: "get_disk_size", query: "df -h", when: os_type == 'linux' } 
             
folders:
  - path: "{{ abap_export_path }}"
    owner: "{{ cloudmigrate_server_sudo_user }}"
    group: "{{ cloudmigrate_server_sudo_user_group }}"
    mode: '0755'
