- name: source
  hosts: "{{ groups['source_master_db'][0] }}"
  tags: source
  vars:
    hostip: "{{ hostvars[groups['source_db'][0]].ansible_host }}"
    source_primary_db: "{{ groups['source_db'][0] }}"
    hana_db_name: "{{ source.sap.db.hana_db_name }}"
  vars_files:
    - ../inventory/group_vars/source_db.yml
  roles:
    - port_status_check
    - create_keys
    - log_mode
    - backups
    - { role: set_network_params, set_params_on: source, when: source_network_params.required == "yes" }
