- name: hana-hsr
  hosts: "{{ groups['target_db'][0] }}"
  #vars:
    #unregister_db: "{{ groups['source_db'][0] }}" # by default site_id is used
  vars_files:
    - ../inventory/group_vars/target_db.yml
  roles:
    - takeover_unregister_hsr
    - { role: sap_db_start_stop, action: start }
    - { role: sap_db_start_stop, action: status }
    - backups

- name: enable site
  hosts: "{{ groups['target_db'][0] }}"
  tasks: 
    - name: enable site on target
      command: sudo su - {{ sid|lower }}adm -c "hdbnsutil -sr_enable --name={{ groups['target_db'][0] }}"
      async: 12000
      poll: 10
      register: en_out
      failed_when: 
        - not (en_out.stdout.find("this site is already enabled as source site")) 
      when: replication.take_over_params.take_over == 'no'

    - debug: 
        var: en_out