---
- hosts: localhost
  tags: abap
  ignore_errors: true
  vars:
    ansible_python_interpreter: "{{ python_interpreter }}"
    playbook_no: "08"
    stage: postmigration_compare
    hostname: "{{ groups['target_ascs'][0] }}"
    hostip: "{{ hostvars[groups['target_ascs'][0]].ansible_host }}"    
  vars_files:
    - ../inventory/group_vars/target_ascs.yml
    - ../inventory/host_vars/{{ groups['target_ascs'][0] }}.yml
  roles:
    - folder_creation
    - sap_abap_execute_queries

- hosts: target_ascs #target_ascs,target_pas,target_aas,target_db
  tags: os
  remote_user: "{{ os_user }}"
  ignore_errors: true
  vars:
    hostip: "{{ hostvars[groups['target_ascs'][0]].ansible_host }}"
    ansible_become: false
  vars_files:  
    - ../inventory/group_vars/target_ascs.yml
    - ../inventory/host_vars/{{ groups['target_ascs'][0] }}.yml
  roles:
    - sap_get_os_command_outputs

- hosts: target_db 
  tags: db
  remote_user: "{{ os_user }}"
  ignore_errors: true
  vars:
    ansible_become: false
    hostip: "{{ hostvars[groups['target_db'][0]].ansible_host }}"
    sql_db_username: "{{ hostvars[groups['target_db'][0]].ansible_user }}"
    # oracle_user: "{{ target.sap.db.oracle_user }}" # this is the default user for oracle user
    # hana_db_name: "{{ target.sap.db.hana_db_name }}" # this is the default hana_db name 
  vars_files:
    - ../inventory/group_vars/target_db.yml
  roles:
    - sap_get_db_queries_outputs

- name: Hana mini checks # if database type is hana
  hosts: target_db
  gather_facts: yes
  become: true
  tags: hanamini
  vars_files:
    - ../inventory/group_vars/target_db.yml
  roles:
      - hana_mini_checks
