---
- name: setting path
  tags: windows
  vars:
     ansible_python_interpreter: "{{ python_interpreter }}"
     python_file_path: env_comparison_win.py
     txt_file_path: windows_excluded_environmentvariable.txt
  set_fact:
     win_env_update: "{{ lookup('first_found', python_file_path) }}"
     win_exlcution_file: "{{ lookup('first_found', txt_file_path.txt) }}"

- name: execute the command to update the env variables with password authentication
  command: python3 {{ win_env_update }} --s_sid={{ source.sap.sid }} --s_hostName="{{ source_hostip }}" --s_userName="{{ env_var_update.env_user.source }}" --s_password="{{ passwords.env_update.source }}" --t_sid="{{ target.sap.sid }}" --t_hostName="{{ target_hostip }}" --t_userName="{{ env_var_update.env_user.target }}" --t_password="{{ passwords.env_update.target }}" --loginMechanism="Password" --pemFile="_NULL" --isSudoUser="False" --exclude_vars_file="{{ win_exlcution_file }}"
  register: result 
  when: env_var_update.env_pem_file_path is not defined

- name: execute the command to update the env variables with pem file authentication
  command: python3 {{path_start_stop}} --s_sid="{{ source.sap.sid }}" --s_hostName="{{ source_hostip }}" --s_userName="{{ env_var_update.env_user.source }}" --s_password="_NULL" --t_sid="{{ target.sap.sid }}" --t_hostName="{{ target_hostip }}" --t_userName="{{ env_var_update.env_user.target }}" --t_password="_NULL" --loginMechanism="PPK" --pemFile="{{ env_var_update.env_pem_file_path }}" --isSudoUser="True" --exclude_vars_file="{{ win_exlcution_file }}"
  register: result1 
  when: env_var_update.env_pem_file_path is defined
  