# If copying ssfs files fails with hostname then the ssfs files will be copied with host ip
- name: copy SSFS files
  block:
    - name: copy files over with hostname 
      ignore_errors: true
      become_method: sudo
      become: yes
      expect:
        command: sudo su - {{ sid | lower }}adm -c "scp -r {{ user }}@{{ rep_source_db }}:{{ item }} {{ item }}"
        responses:
          (?i)continue connecting: "yes"
          (?i)password: "{{ root_password }}"
      loop:
        - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ sid|upper }}.DAT 
        - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ sid|upper }}.KEY
      register: ssfs_files

    - name: copy files over with host ip
      become_method: sudo
      become: yes
      expect:
        command: sudo su - {{ sid | lower }}adm -c "scp -r {{ user }}@{{ copy_files.host_ip }}:{{ item }} {{ item }}"
        responses:
          (?i)continue connecting: "yes"
          (?i)password: "{{ root_password }}"
      loop:
        - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ sid|upper }}.DAT 
        - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ sid|upper }}.KEY
      when: ssfs_files.results[0].stdout is search ("Name or service not known")

  when: topology == 'NONHA' or topology == 'DR'

- name: copy files over
  command: sudo su - {{ sid | lower }}adm -c "sshpass -p '{{ root_password }}' scp -r {{ user }}@{{ rep_source_db }}:{{ item }} {{ item }}"
  loop:
    - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ sid|upper }}.DAT 
    - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ sid|upper }}.KEY
  when: topology == 'HA'