---

- name: copy files over
  command: sudo su - {{ sid | lower }}adm -c "scp -o StrictHostKeyChecking=no {{ sid | lower }}adm@{{ rep_source_db }}:{{ item }} {{ item }}"
  async: 12000
  poll: 10
  loop:
    - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ sid|upper }}.DAT 
    - /usr/sap/{{ sid|upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ sid|upper }}.KEY
